-- MySQL Script generated by MySQL Workbench
-- Fri Oct  6 12:52:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema oasys
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oasys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oasys` DEFAULT CHARACTER SET utf8mb4 ;
USE `oasys` ;

-- -----------------------------------------------------
-- Table `oasys`.`Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oasys`.`Member` ;

CREATE TABLE IF NOT EXISTS `oasys`.`Member` (
  `member_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `member_subId` VARCHAR(15) NULL DEFAULT NULL,
  `member_faceId` VARCHAR(15) NULL DEFAULT NULL,
  `member_nickName` VARCHAR(255) NOT NULL,
  `member_gender` VARCHAR(6) NULL DEFAULT NULL,
  `member_phone` VARCHAR(11) NOT NULL,
  `member_role` VARCHAR(6) NULL DEFAULT '0',
  `member_createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `member_updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `member_age` INT(11) NULL DEFAULT NULL,
  `member_isDeleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`member_id`),
  INDEX `idx_faceId` (`member_faceId` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `oasys`.`TellerType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oasys`.`TellerType` ;

CREATE TABLE IF NOT EXISTS `oasys`.`TellerType` (
  `tellerType_id` BIGINT(20) NOT NULL,
  `tellerType_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`tellerType_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- `oasys`.`Member` Data
-- -----------------------------------------------------

INSERT INTO `oasys`.`Member` (`member_id`,`member_subId`,`member_faceId`,`member_nickName`,`member_gender`,`member_phone`,`member_role`,`member_createdAt`,`member_updatedAt`,`member_age`,`member_isDeleted`) VALUES (1,'4','user4','kkkk4','man','12345678900','0','2023-10-02 12:48:37','2023-10-02 12:48:37',30,0);
INSERT INTO `oasys`.`Member` (`member_id`,`member_subId`,`member_faceId`,`member_nickName`,`member_gender`,`member_phone`,`member_role`,`member_createdAt`,`member_updatedAt`,`member_age`,`member_isDeleted`) VALUES (2,'RU8V7DGIX4','J3IWHY6W8B','이순재','MALE','01055143767','NORMAL','2023-10-05 14:34:38','2023-10-05 14:34:38',80,0);
INSERT INTO `oasys`.`Member` (`member_id`,`member_subId`,`member_faceId`,`member_nickName`,`member_gender`,`member_phone`,`member_role`,`member_createdAt`,`member_updatedAt`,`member_age`,`member_isDeleted`) VALUES (3,'AHBH3YASJ6','AQF4X0666N','나문희','FEMALE','01092458696','NORMAL','2023-10-05 14:36:20','2023-10-05 14:36:20',78,0);


-- -----------------------------------------------------
-- `oasys`.`TellerType` Data
-- -----------------------------------------------------

INSERT INTO `oasys`.`TellerType` (`tellerType_id`,`tellerType_name`) VALUES (1,'통장 · 계좌');
INSERT INTO `oasys`.`TellerType` (`tellerType_id`,`tellerType_name`) VALUES (2,'카드');
INSERT INTO `oasys`.`TellerType` (`tellerType_id`,`tellerType_name`) VALUES (3,'인터넷뱅킹');
INSERT INTO `oasys`.`TellerType` (`tellerType_id`,`tellerType_name`) VALUES (4,'대출 · 외환');